// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  conceptsSidebar: [
    {
      type: 'category',
      label: 'ADG Concepts',
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
  ],

  standardsSidebar: [
    {
      type: 'category',
      label: 'ADG Standards',
      items: [{ type: 'autogenerated', dirName: 'standards' }],
    },
  ],

  frameworkSidebar: [
    {
      type: 'category',
      label: 'ADG Framework',
      items: [{ type: 'autogenerated', dirName: 'framework' }],
    },
  ],
};

export default sidebars;